FROM debian:stable-slim
MAINTAINER Taito United <support@taitounited.fi>

USER root
COPY . /taito-cli-deps
WORKDIR /tmp

RUN /taito-cli-deps/tools/install-basic.sh

# Install docker (required for executing CI/CD builds on container)
RUN /taito-cli-deps/tools/install-docker.sh

# Install docker-compose (required for CI/CD tests)
RUN /taito-cli-deps/tools/install-docker-compose.sh

ENV NODEJS_VERSION 10.x
RUN /taito-cli-deps/tools/install-nodejs.sh

RUN /taito-cli-deps/tools/install-helm.sh

# Install postgres and mysql client
RUN /taito-cli-deps/tools/install-db-clients.sh

RUN /taito-cli-deps/tools/install-sqitch.sh

# Install aws cli and aws-iam-authenticator
RUN /taito-cli-deps/tools/install-aws.sh

# Install bats for Taito CLI unit testing
RUN /taito-cli-deps/tools/install-bats.sh

# Initialize root user
RUN /taito-cli-deps/tools/user-init.sh root

ENTRYPOINT ["bash"]
